namespace GymManagement.Domain.Entities;

public enum WorkoutPlanAuditAction
{
    Created = 0,
    Updated = 1,
    ExerciseAdded = 2,
    ExerciseUpdated = 3,
    ExerciseRemoved = 4,
    Deleted = 5,
    WarmupCreated = 10,
    WarmupUpdated = 11,
    WarmupDeleted = 12,
    StretchCreated = 13,
    StretchUpdated = 14,
    StretchDeleted = 15,
    WarmupAddedToWorkout = 16,
    WarmupRemovedFromWorkout = 17,
    StretchAddedToWorkout = 18,
    StretchRemovedFromWorkout = 19,
    CategoryCreated = 20,
    CategoryUpdated = 21,
    CategoryDeleted = 22,
    WarmupAddedToCategory = 23,
    WarmupRemovedFromCategory = 24,
    StretchAddedToCategory = 25,
    StretchRemovedFromCategory = 26,
    WorkoutPlanAutoAssignmentChanged = 27,
    PlanCloned = 28,
    VersionCreated = 29,
    TemplateChanged = 30,
    CategoryChanged = 31,
    DayChanged = 32,
}
