import type {
  CleaningLog,
  Equipment,
  Expense,
  MaintenanceLog,
  Vendor,
} from '../types'

const iso = (offsetDays: number): string => {
  const d = new Date()
  d.setDate(d.getDate() + offsetDays)
  return d.toISOString()
}

export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-001',
    name: 'Treadmill X7',
    category: 'Cardio',
    brand: 'PulseRun',
    serialNumber: 'PR-TRX7-0001',
    location: 'Cardio Zone',
    purchaseDate: iso(-720),
    purchaseCost: 185000,
    status: 'OPERATIONAL',
    nextServiceDate: iso(12),
  },
  {
    id: 'eq-002',
    name: 'Rowing Ergometer',
    category: 'Cardio',
    brand: 'WaveFit',
    serialNumber: 'WF-RE2-2040',
    location: 'Cardio Zone',
    purchaseDate: iso(-420),
    purchaseCost: 78000,
    status: 'UNDER_MAINTENANCE',
    nextServiceDate: iso(-3),
  },
  {
    id: 'eq-003',
    name: 'Smith Machine',
    category: 'Strength',
    brand: 'IronCore',
    serialNumber: 'IC-SM-1152',
    location: 'Weight Floor',
    purchaseDate: iso(-960),
    purchaseCost: 120000,
    status: 'OPERATIONAL',
    nextServiceDate: iso(45),
  },
  {
    id: 'eq-004',
    name: 'Cable Crossover',
    category: 'Strength',
    brand: 'IronCore',
    serialNumber: 'IC-CC-3381',
    location: 'Weight Floor',
    purchaseDate: iso(-300),
    purchaseCost: 96000,
    status: 'OUT_OF_ORDER',
    nextServiceDate: iso(-10),
    notes: 'Pulley cable snapped. Replacement ordered.',
  },
  {
    id: 'eq-005',
    name: 'Battle Rope Set',
    category: 'Functional',
    brand: 'FlexCore',
    location: 'Functional Zone',
    purchaseDate: iso(-120),
    purchaseCost: 4500,
    status: 'OPERATIONAL',
  },
  {
    id: 'eq-006',
    name: 'Kettlebell Rack 8-32kg',
    category: 'Accessory',
    brand: 'FlexCore',
    location: 'Functional Zone',
    purchaseDate: iso(-540),
    purchaseCost: 38000,
    status: 'OPERATIONAL',
    nextServiceDate: iso(80),
  },
  {
    id: 'eq-007',
    name: 'Spin Bike Pro',
    category: 'Cardio',
    brand: 'PulseRun',
    serialNumber: 'PR-SB-8812',
    location: 'Studio A',
    purchaseDate: iso(-210),
    purchaseCost: 52000,
    status: 'OPERATIONAL',
    nextServiceDate: iso(3),
  },
  {
    id: 'eq-008',
    name: 'Leg Press 45°',
    category: 'Strength',
    brand: 'IronCore',
    serialNumber: 'IC-LP-0052',
    location: 'Weight Floor',
    purchaseDate: iso(-1100),
    purchaseCost: 145000,
    status: 'RETIRED',
    notes: 'Replaced by LP Pro in January.',
  },
]

export const MOCK_MAINTENANCE: MaintenanceLog[] = [
  {
    id: 'ml-001',
    equipmentId: 'eq-002',
    equipmentName: 'Rowing Ergometer',
    type: 'REPAIR',
    performedAt: iso(-2),
    performedBy: 'Arjun (in-house)',
    cost: 3200,
    description: 'Replaced damper cable and lubricated chain.',
    nextServiceDate: iso(60),
  },
  {
    id: 'ml-002',
    equipmentId: 'eq-004',
    equipmentName: 'Cable Crossover',
    type: 'INSPECTION',
    performedAt: iso(-10),
    performedBy: 'Meera (vendor)',
    cost: 0,
    description: 'Snapped cable — replacement ordered, unit tagged out-of-order.',
  },
  {
    id: 'ml-003',
    equipmentId: 'eq-001',
    equipmentName: 'Treadmill X7',
    type: 'ROUTINE',
    performedAt: iso(-18),
    performedBy: 'Arjun (in-house)',
    cost: 800,
    description: 'Belt alignment + motor dusted. No issues found.',
    nextServiceDate: iso(12),
  },
  {
    id: 'ml-004',
    equipmentId: 'eq-007',
    equipmentName: 'Spin Bike Pro',
    type: 'ROUTINE',
    performedAt: iso(-35),
    performedBy: 'Arjun (in-house)',
    cost: 500,
    description: 'Pedal tightened, resistance knob calibrated.',
    nextServiceDate: iso(3),
  },
  {
    id: 'ml-005',
    equipmentId: 'eq-003',
    equipmentName: 'Smith Machine',
    type: 'INSPECTION',
    performedAt: iso(-55),
    performedBy: 'Meera (vendor)',
    cost: 1500,
    description: 'Safety catches tested, counterweight balanced.',
  },
]

export const MOCK_EXPENSES: Expense[] = [
  {
    id: 'ex-001',
    category: 'Utilities',
    vendor: 'TPDDL Electricity',
    amount: 48200,
    incurredAt: iso(-6),
    description: 'Monthly electricity bill',
    status: 'PAID',
  },
  {
    id: 'ex-002',
    category: 'Maintenance',
    vendor: 'IronCore Services',
    amount: 12500,
    incurredAt: iso(-3),
    description: 'Cable crossover repair parts',
    status: 'PENDING',
  },
  {
    id: 'ex-003',
    category: 'Supplies',
    vendor: 'CleanPro Supplies',
    amount: 6800,
    incurredAt: iso(-12),
    description: 'Sanitizer, towels, cleaning spray refill',
    status: 'PAID',
  },
  {
    id: 'ex-004',
    category: 'Marketing',
    vendor: 'BoostAds',
    amount: 18000,
    incurredAt: iso(-20),
    description: 'Instagram / Meta ad credits (monthly)',
    status: 'PAID',
  },
  {
    id: 'ex-005',
    category: 'Salaries',
    amount: 312000,
    incurredAt: iso(-1),
    description: 'Staff payroll run',
    status: 'PAID',
  },
  {
    id: 'ex-006',
    category: 'Utilities',
    vendor: 'DJB Water Board',
    amount: 5400,
    incurredAt: iso(-10),
    description: 'Water supply + tanker top-up',
    status: 'PAID',
  },
  {
    id: 'ex-007',
    category: 'Other',
    amount: 4200,
    incurredAt: iso(-40),
    description: 'Replacement wall mirror (studio A)',
    status: 'PAID',
  },
]

export const MOCK_CLEANING: CleaningLog[] = [
  {
    id: 'cl-001',
    area: 'Cardio Zone',
    shift: 'MORNING',
    scheduledAt: iso(0),
    performedBy: 'Ravi',
    performedAt: iso(0),
    tasks: [
      { id: 't1', label: 'Wipe all machine handles', done: true },
      { id: 't2', label: 'Sanitize display panels', done: true },
      { id: 't3', label: 'Refill hand-sanitizer dispensers', done: true },
      { id: 't4', label: 'Vacuum floor mats', done: false },
    ],
  },
  {
    id: 'cl-002',
    area: 'Weight Floor',
    shift: 'MORNING',
    scheduledAt: iso(0),
    tasks: [
      { id: 't1', label: 'Rack all dumbbells/plates', done: true },
      { id: 't2', label: 'Wipe benches and pads', done: true },
      { id: 't3', label: 'Mop floor', done: false },
      { id: 't4', label: 'Spray disinfectant on grips', done: false },
    ],
  },
  {
    id: 'cl-003',
    area: 'Locker Rooms',
    shift: 'AFTERNOON',
    scheduledAt: iso(0),
    tasks: [
      { id: 't1', label: 'Clean toilets', done: false },
      { id: 't2', label: 'Replace towels', done: false },
      { id: 't3', label: 'Mop floor', done: false },
      { id: 't4', label: 'Restock toiletries', done: false },
    ],
  },
  {
    id: 'cl-004',
    area: 'Studio A',
    shift: 'EVENING',
    scheduledAt: iso(0),
    tasks: [
      { id: 't1', label: 'Wipe mirrors', done: false },
      { id: 't2', label: 'Stack mats', done: false },
      { id: 't3', label: 'Sweep floor', done: false },
    ],
  },
  {
    id: 'cl-005',
    area: 'Reception',
    shift: 'EVENING',
    scheduledAt: iso(0),
    tasks: [
      { id: 't1', label: 'Sanitize counter + card reader', done: false },
      { id: 't2', label: 'Empty trash bins', done: false },
      { id: 't3', label: 'Tidy brochures', done: false },
    ],
  },
]

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'v-001',
    name: 'IronCore Services',
    category: 'Maintenance',
    contactPerson: 'Meera Kapoor',
    email: 'meera@ironcore.example',
    phone: '+91 98100 12345',
    rating: 4.6,
    onContract: true,
    notes: 'Quarterly service contract, priority response within 24h.',
  },
  {
    id: 'v-002',
    name: 'CleanPro Supplies',
    category: 'Cleaning',
    contactPerson: 'Raghav Mehta',
    email: 'sales@cleanpro.example',
    phone: '+91 97100 55511',
    rating: 4.2,
    onContract: true,
  },
  {
    id: 'v-003',
    name: 'BoostAds Digital',
    category: 'Other',
    contactPerson: 'Priya Nanda',
    email: 'priya@boostads.example',
    rating: 4.0,
    onContract: false,
  },
  {
    id: 'v-004',
    name: 'FlexCore Equipment',
    category: 'Equipment',
    contactPerson: 'Vikram Singh',
    phone: '+91 98765 00022',
    rating: 4.4,
    onContract: false,
  },
  {
    id: 'v-005',
    name: 'NetPulse IT',
    category: 'IT',
    contactPerson: 'Anita Rao',
    email: 'anita@netpulse.example',
    rating: 3.9,
    onContract: true,
    notes: 'Managed network + POS maintenance.',
  },
]
